# Nearest Points Exercise

Tamás Gál (tamas.gal@fau.de)

The latest version of this notebook is available at [https://github.com/Asterics2020-Obelics](https://github.com/Asterics2020-Obelics/School2019/tree/master/numpy)

In [1]:
import numpy as np
import sys

print("Python version: {0}\n"
      "NumPy version: {1}"
      .format(sys.version, np.__version__))

Python version: 3.7.2 (default, Jan 10 2019, 10:02:28) 
[GCC 8.2.1 20181127]
NumPy version: 1.16.2


## Given an array of points (in 3D), find the nearest point for each one.

In [2]:
N = 500
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[0.00368258, 0.84547533, 0.0158545 ],
       [0.37083843, 0.06757693, 0.28639038],
       [0.73109532, 0.93115284, 0.32163347],
       ...,
       [0.02524286, 0.40163642, 0.9737498 ],
       [0.41788417, 0.08092533, 0.69547339],
       [0.21556833, 0.11971078, 0.5566289 ]])

### Solution

In [3]:
N = 4
n_dims = 3
points = np.random.random((N, n_dims))
points

array([[0.61796678, 0.52968887, 0.67180841],
       [0.15925767, 0.05652312, 0.37038653],
       [0.80448909, 0.68714072, 0.0224116 ],
       [0.83354431, 0.80402313, 0.86704773]])

In [4]:
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

array([3, 0, 0, 0])

### Discussion

In [5]:
points

array([[0.61796678, 0.52968887, 0.67180841],
       [0.15925767, 0.05652312, 0.37038653],
       [0.80448909, 0.68714072, 0.0224116 ],
       [0.83354431, 0.80402313, 0.86704773]])

In [6]:
points.shape

(4, 3)

In [7]:
reshaped_points = points.reshape(N, 1, n_dims)
reshaped_points

array([[[0.61796678, 0.52968887, 0.67180841]],

       [[0.15925767, 0.05652312, 0.37038653]],

       [[0.80448909, 0.68714072, 0.0224116 ]],

       [[0.83354431, 0.80402313, 0.86704773]]])

In [8]:
reshaped_points.shape

(4, 1, 3)

In [9]:
differences = reshaped_points - points
differences

array([[[ 0.        ,  0.        ,  0.        ],
        [ 0.45870911,  0.47316575,  0.30142188],
        [-0.18652231, -0.15745185,  0.64939681],
        [-0.21557753, -0.27433426, -0.19523932]],

       [[-0.45870911, -0.47316575, -0.30142188],
        [ 0.        ,  0.        ,  0.        ],
        [-0.64523141, -0.6306176 ,  0.34797493],
        [-0.67428664, -0.74750001, -0.4966612 ]],

       [[ 0.18652231,  0.15745185, -0.64939681],
        [ 0.64523141,  0.6306176 , -0.34797493],
        [ 0.        ,  0.        ,  0.        ],
        [-0.02905522, -0.11688241, -0.84463613]],

       [[ 0.21557753,  0.27433426,  0.19523932],
        [ 0.67428664,  0.74750001,  0.4966612 ],
        [ 0.02905522,  0.11688241,  0.84463613],
        [ 0.        ,  0.        ,  0.        ]]])

In [10]:
print(reshaped_points.shape, " - ", points.shape, " => ", differences.shape)

(4, 1, 3)  -  (4, 3)  =>  (4, 4, 3)


In [11]:
distances = np.sum(differences**2, axis=2)
distances

array([[0.        , 0.52515502, 0.48129787, 0.15985135],
       [0.52515502, 0.        , 0.93508868, 1.26009108],
       [0.48129787, 0.93508868, 0.        , 0.7279159 ],
       [0.15985135, 1.26009108, 0.7279159 , 0.        ]])

In [12]:
distances.shape

(4, 4)

In [13]:
distances

array([[0.        , 0.52515502, 0.48129787, 0.15985135],
       [0.52515502, 0.        , 0.93508868, 1.26009108],
       [0.48129787, 0.93508868, 0.        , 0.7279159 ],
       [0.15985135, 1.26009108, 0.7279159 , 0.        ]])

In [14]:
# get rid of self-distances first ;)
distances[np.diag_indices_from(distances)] = np.inf

In [15]:
distances

array([[       inf, 0.52515502, 0.48129787, 0.15985135],
       [0.52515502,        inf, 0.93508868, 1.26009108],
       [0.48129787, 0.93508868,        inf, 0.7279159 ],
       [0.15985135, 1.26009108, 0.7279159 ,        inf]])

In [16]:
nearest_points = np.argmin(distances, axis=1)
nearest_points

array([3, 0, 0, 0])

### Comparing to `scikit-learn`

In [17]:
nearest_points

array([3, 0, 0, 0])

In [18]:
from sklearn.neighbors import NearestNeighbors
_, indices = NearestNeighbors().fit(points).kneighbors(points, 2)
indices[:, 1]

array([3, 0, 0, 0])

In [19]:
%timeit _, indices = NearestNeighbors().fit(points).kneighbors(points, 2)

190 µs ± 1.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [20]:
%%timeit
distances = np.sum((points.reshape(N, 1, n_dims) - points)**2, axis=2)
distances[np.diag_indices_from(distances)] = np.inf
np.argmin(distances, axis=1)

26.5 µs ± 260 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Depending on the data size, our implementation may be faster!